/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Wed Jul 31 19:53:04 2013
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


