/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Mar 22 11:24:31 2014
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>
void pmu_drv_tool_customization_init(void)
{
}


